# Generated by Django 4.0.3 on 2022-03-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_kr', models.CharField(default='디폴트 서비스', max_length=100)),
                ('service_en', models.CharField(default='DEFAULT SERVICE', max_length=100)),
                ('logo_img', models.ImageField(blank=True, default='', null=True, upload_to='logo_imgs')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('초대 코드', 'code'), ('초대 링크', 'link')], max_length=10)),
                ('invitation', models.CharField(default='DEFAULT INVITATION', max_length=2000)),
                ('desc', models.TextField(blank=True)),
                ('totalClicks', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='main.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='main.invitation')),
            ],
        ),
    ]
