# Generated by Django 4.0.3 on 2022-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_logo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='ip_address',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
