# Generated by Django 4.0.3 on 2022-04-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_click_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
