# Generated by Django 4.0.3 on 2022-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicecategory_remove_invitation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_kakao_id',
            field=models.IntegerField(default=1),
        ),
    ]
